name: Build & Deploy Flutter Web to Vercel

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          # Use a specific/latest version string instead of the ambiguous 'stable' channel
          # to avoid resolution failures in the action environment.
          flutter-version: 'latest'

      - name: Install dependencies
        run: flutter pub get

      - name: Ensure web tooling and build release
        run: |
          # Make sure web is enabled and Flutter SDK is up-to-date in the runner
          flutter channel stable
          flutter upgrade --force
          flutter config --enable-web
          flutter pub get
          # build the web release (NO space between -- and release)
          flutter build web --release

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          # deploy the generated build/web folder to Vercel
          vercel --prod ./build/web --token $VERCEL_TOKEN --confirm
